package scenarios

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.http.response.Response

import utils.{Common, Environment, Headers}

object Caseworker_ManageHearing {

  val BaseURL = Environment.baseURL

  val MinThinkTime = Environment.minThinkTime
  val MaxThinkTime = Environment.maxThinkTime
  val caseIdFeeder = csv("UserDataHearing.csv").circular
  val TypeHearingFeeder = csv("TypeOfHearing.csv").random
  val WordingFeeder = csv("WordingOfHearing.csv").random

  val OpenCaseIssed =
        group("XUI_PCS_Caseworker_AddHearing_03_OpenCaseIssuedRecord") {
            feed(caseIdFeeder)
				exec(http("XUI_PCS_Caseworker_AddHearing_03_OpenCaseIssuedRecord")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
				)
                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN1")))

				.exec(http("/data/internal/searchCases?ctid=PCS&use_case=WORKBASKET&view=WORKBASKET&state=CASE_ISSUED&$page=1")
					.post("/data/internal/searchCases?ctid=PCS&use_case=WORKBASKET&view=WORKBASKET&state=CASE_ISSUED&page=1")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Origin", BaseURL)
					.header("Priority", "u=0")
                    .formParam("X-XSRF-TOKEN", "${XSRF-TOKEN1}")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.body(StringBody("{\"size\":25}"))
                    .check(substring("columns"))
				)
				.exec(http("/data/internal/cases/#{caseId}")
					.get("/data/internal/cases/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("experimental", "true")
					.header("Priority", "u=0")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-case-view.v2+json")
					.header("Content-Type", "application/json")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL)
					.header("Accept", "application/json, text/plain, */*")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)
                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN2")))

				.exec(http("/api/role-access/roles/manageLabellingRoleAssignment/#{caseId}")
					.post("/api/role-access/roles/manageLabellingRoleAssignment/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", s"$BaseURL/cases")
					.header("Origin", BaseURL)
					.header("Accept", "application/json, text/plain, */*")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN2}")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.body(StringBody("{}"))
                    .check(status.in(204))
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", s"$BaseURL/cases")
					.header("Accept", "application/json, text/plain, */*")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)
				.exec(http("/aggregated/caseworkers/:uid/jurisdictions")
					.get("/aggregated/caseworkers/:uid/jurisdictions")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", s"$BaseURL/cases")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.queryParam("access", "read")
                    .check(substring("Civil Possession"))
				)

                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN3")))

				.exec(http("/workallocation/case/task/#{caseId}")
					.post("/workallocation/case/task/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", s"$BaseURL/cases")
					.header("Origin", BaseURL)
					.header("Accept", "application/json, text/plain, */*")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN3}")
					.header("Content-Type", "application/json")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.body(StringBody("{\"refined\":true}"))
                    .check(status.in(200))
				)

				.pause(MinThinkTime, MaxThinkTime)
    }
    val AddHearing =
        group("XUI_PCS_Caseworker_AddHearing_04_SelectManageHearingDropDown") {
				exec(http("XUI_PCS_Caseworker_AddHearing_04_SelectManageHearingDropDown")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.exec(http("/workallocation/case/tasks/#{caseId}/event/manageHearing/caseType/PCS/jurisdiction/PCS")
					.get("/workallocation/case/tasks/#{caseId}/event/manageHearing/caseType/PCS/jurisdiction/PCS")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Priority", "u=0")
					.header("Content-Type", "application/json")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(jsonPath("$.task_required_for_event").ofType[Boolean].is(false))
				)
				.exec(http("/data/internal/profile")
					.get("/data/internal/profile")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("experimental", "true")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-user-profile.v2+json;charset=UTF-8")
					.header("Content-Type", "application/json")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(jsonPath("$.jurisdictions[0].name").is("Civil Possession"))
				)
				.exec(http("/data/internal/cases/#{caseId}/event-triggers/manageHearing")
					.get("/data/internal/cases/#{caseId}/event-triggers/manageHearing")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("experimental", "true")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-start-event-trigger.v2+json;charset=UTF-8")
					.header("Content-Type", "application/json")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.queryParam("ignore-warning", "false")
					.check(regex("event_token\":\"(.*?)\",\"wizard_pages").saveAs("event_token"))
                    .check(jsonPath("$.case_fields[?(@.id == 'hearingLocation')].value").saveAs("hearingLocation"))
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/cases/case-details/PCS/PCS/#{caseId}")
					.header("Accept", "application/json, text/plain, */*")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)

                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN4")))

				.pause(MinThinkTime, MaxThinkTime)
            }

    val AddHearingDetails =
        group("XUI_PCS_Caseworker_AddHearing_05_AddDetails") {
            feed(TypeHearingFeeder)
            feed(WordingFeeder)
				exec(http("XUI_PCS_Caseworker_AddHearing_05_AddDetails")
					.post("/data/case-types/PCS/validate?pageId=manageHearinghearingDetails")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Origin", BaseURL)
					.header("experimental", "true")
					.header("Priority", "u=0")
					.header("Client-Context", "eyJjbGllbnRfY29udGV4dCI6eyJ1c2VyX2xhbmd1YWdlIjp7Imxhbmd1YWdlIjoiZW4ifX19")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.case-data-validate.v2+json;charset=UTF-8")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN4}")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.body(StringBody("{\"data\":{\"hearingLocation\":\"#{hearingLocation}\",\"hearing_Type\":\"#{TypeofHearing}\",\"hearing_NoticeWording\":\"#{WordingOfHearing}\",\"hearing_Date\":\"2028-02-01T00:00:00.000\",\"hearing_DurationDays\":\"1\",\"hearing_DurationHours\":\"1\",\"hearing_DurationMinutes\":\"10\",\"hearing_Notes\":\"hearing testing for further discussion on claim issues\",\"hearing_IssueNotice\":\"NO\",\"hearing_AdditionalInformation\":\"Testing\"},\"event\":{\"id\":\"manageHearing\",\"summary\":\"\",\"description\":\"\"},\"event_data\":{\"hearingLocation\":\"#{hearingLocation}\",\"hearing_Type\":\"POSSESSION\",\"hearing_NoticeWording\":\"ADJ\",\"hearing_Date\":\"2028-02-01T00:00:00.000\",\"hearing_DurationDays\":\"1\",\"hearing_DurationHours\":\"1\",\"hearing_DurationMinutes\":\"10\",\"hearing_Notes\":\"hearing testing for further discussion on claim issues\",\"hearing_IssueNotice\":\"NO\",\"hearing_AdditionalInformation\":\"Testing\"},\"event_token\":\"#{event_token}\",\"ignore_warning\":false,\"case_reference\":\"#{caseId}\"}"))
                    .check(jsonPath("$.data.hearing_Type").is("POSSESSION"))
				)
				.pause(MinThinkTime, MaxThinkTime)
			}

        .group("XUI_PCS_Caseworker_AddHearing_06_ManageHearing") {
				exec(http("XUI_PCS_Caseworker_AddHearing_06_ManageHearing")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN5")))

				.exec(http("/data/cases/#{caseId}/events")
					.post("/data/cases/#{caseId}/events")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Origin", BaseURL)
					.header("experimental", "true")
					.header("Priority", "u=0")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.create-event.v2+json;charset=UTF-8")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN5}")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.header("Sec-Fetch-Dest", "empty")
					.body(StringBody("{\"data\":{\"hearingLocation\":\"#{hearingLocation}\",\"hearing_Type\":\"#{TypeofHearing}\",\"hearing_NoticeWording\":\"#{WordingOfHearing}\",\"hearing_Date\":\"2028-02-01T00:00:00\",\"hearing_DurationDays\":\"1\",\"hearing_DurationHours\":\"1\",\"hearing_DurationMinutes\":\"10\",\"hearing_Notes\":\"hearing testing for further discussion on claim issues\",\"hearing_IssueNotice\":\"NO\",\"hearing_AdditionalInformation\":\"Testing\"},\"event\":{\"id\":\"manageHearing\",\"summary\":\"\",\"description\":\"\"},\"event_token\":\"#{event_token}\",\"ignore_warning\":false}"))
                    .check(jsonPath("$.state").is("CASE_ISSUED"))
				)
				.exec(http("/data/internal/cases/#{caseId}")
					.get("/data/internal/cases/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("experimental", "true")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-case-view.v2+json")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(jsonPath("$.case_type.name").is("Possession"))
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/cases/case-details/PCS/PCS/#{caseId}/trigger/manageHearing/submit")
					.header("Accept", "application/json, text/plain, */*")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
		 		)
				.pause(MinThinkTime, MaxThinkTime)
			}
     val CloseCase =
        group("XUI_PCS_Caseworker_AddHearing_07_ClickClose&Return") {
				exec(http("XUI_PCS_Caseworker_AddHearing_07_ClickClose&Return")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN6")))

				.exec(http("/api/role-access/roles/manageLabellingRoleAssignment/#{caseId}")
					.post("/api/role-access/roles/manageLabellingRoleAssignment/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/cases/case-details/PCS/PCS/#{caseId}/trigger/manageHearing/confirm")
					.header("Origin", BaseURL)
					.header("Priority", "u=0")
					.header("Accept", "application/json, text/plain, */*")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN6}")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.body(StringBody("{}"))
                    .check(status.in(204))
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/cases/case-details/PCS/PCS/#{caseId}/trigger/manageHearing/confirm")
					.header("Priority", "u=0")
					.header("Accept", "application/json, text/plain, */*")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/cases/case-details/PCS/PCS/#{caseId}/trigger/manageHearing/confirm")
					.header("Priority", "u=0")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/cases/case-details/PCS/PCS/#{caseId}")
					.header("Accept", "application/json, text/plain, */*")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)
                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN7")))

				.exec(http("/workallocation/case/task/#{caseId}")
					.post("/workallocation/case/task/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Origin", BaseURL)
					.header("Accept", "application/json, text/plain, */*")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN7}")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.body(StringBody("{\"refined\":true}"))
                    .check(status.in(200))
				)
				.pause(MinThinkTime, MaxThinkTime)
			}
    val HistoryView =
        group("XUI_PCS_Caseworker_AddHearing_08_clickhistoryTab") {
				exec(http("XUI_PCS_Caseworker_AddHearing_08_clickhistoryTab")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/cases/case-details/PCS/PCS/#{caseId}")
					.header("Priority", "u=0")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)
				.pause(MinThinkTime, MaxThinkTime)
			} 

    val SearchCaseId =
       group("XUI_PCS_Caseworker_AmendHearing_09_SearchRecord") {
				exec(http("XUI_PCS_Caseworker_AmendHearing_09_SearchRecord")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Priority", "u=0")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)
				
				.exec(http("/aggregated/caseworkers/:uid/jurisdictions")
					.get("/aggregated/caseworkers/:uid/jurisdictions")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/search")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.queryParam("access", "read")
                    .check(jsonPath("$[0].caseTypes[0].name").is("Possession"))
				)
                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN8")))

				.exec(http("/api/globalsearch/results")
					.post("/api/globalsearch/results")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("x-dtreferer", BaseURL + "/search")
					.header("Origin", BaseURL)
					.header("Accept", "application/json, text/plain, */*")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN8}")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.header("Sec-Fetch-Dest", "empty")
					.body(StringBody("{\"searchCriteria\":{\"CCDCaseTypeIds\":null,\"CCDJurisdictionIds\":[\"IA\",\"Civil\",\"PRIVATELAW\",\"PUBLICLAW\",\"SSCS\",\"ST_CIC\",\"EMPLOYMENT\",\"PCS\",\"PROBATE\"],\"caseManagementBaseLocationIds\":null,\"caseManagementRegionIds\":null,\"caseReferences\":[\"#{caseId}\"],\"otherReferences\":null,\"parties\":[],\"stateIds\":null},\"sortCriteria\":null,\"maxReturnRecordCount\":25,\"startRecordNumber\":1}"))
                    .check(jsonPath("$.results[0].CCDJurisdictionId").is("PCS"))
				)
				.pause(MinThinkTime, MaxThinkTime)
			}
    val VeiwCaseId =
       group("XUI_PCS_Caseworker_AmendHearing_10_clcikview") {
				exec(http("XUI_PCS_Caseworker_AmendHearing_10_clcikview")
					.get("/auth/isAuthenticated")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.exec(http("/data/internal/cases/#{caseId}")
					.get("/data/internal/cases/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("experimental", "true")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-case-view.v2+json")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)

                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN9")))

				.exec(http("/api/role-access/roles/manageLabellingRoleAssignment/${caseId}")
					.post("/api/role-access/roles/manageLabellingRoleAssignment/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Origin", BaseURL)
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN9}")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.body(StringBody("{}"))
                    .check(status.in(204))
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.header("Sec-Fetch-Dest", "empty")
                    .check(substring("PCS"))
				)

                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN10")))

				.exec(http("/workallocation/case/task/#{caseId}")
					.post("/workallocation/case/task/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Origin", BaseURL)
					.header("Accept", "application/json, text/plain, */*")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN10}")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.body(StringBody("{\"refined\":true}"))
				)
				.exec(http("/aggregated/caseworkers/:uid/jurisdictions")
					.get("/aggregated/caseworkers/:uid/jurisdictions")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.header("Sec-Fetch-Dest", "empty")
					.queryParam("access", "read")
                    .check(substring("PCS"))
				)
				.pause(MinThinkTime, MaxThinkTime)
			}
    val MangehearingTab =
       group("XUI_PCS_Caseworker_AmendHearing_11_ManagehearingTab") {
				exec(http("XUI_PCS_Caseworker_AmendHearing_11_ManagehearingTab")
					.get("/workallocation/case/tasks/#{caseId}/event/manageHearing/caseType/PCS/jurisdiction/PCS")
					.headers(Headers.commonHeader)
					.header("Priority", "u=0")
					.header("Accept", "application/json")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(jsonPath("$.task_required_for_event").ofType[Boolean].is(false))
				)
				.exec(http("/data/internal/profile")
					.get("/data/internal/profile")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("experimental", "true")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-user-profile.v2+json;charset=UTF-8")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.exec(http("/data/internal/cases/#{caseId}/event-triggers/manageHearing")
					.get("/data/internal/cases/#{caseId}/event-triggers/manageHearing")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("experimental", "true")
					.header("Client-Context", "eyJjbGllbnRfY29udGV4dCI6eyJ1c2VyX2xhbmd1YWdlIjp7Imxhbmd1YWdlIjoiZW4ifX19")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-start-event-trigger.v2+json;charset=UTF-8")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.queryParam("ignore-warning", "false")
					.check(regex("event_token\":\"(.*?)\",\"wizard_pages").saveAs("event_token1"))
					.check(regex("hearing_HearingSummaryMarkdown\",\"label\":\"\",\"hidden\":null,\"value\":\"(.*?)&nbsp;").saveAs("HearingSummaryMarkdown"))
                    .check(regex(""""id"\s*:\s*"hearing_HearingId"[\s\S]*?"value"\s*:\s*(\d+)""").saveAs("hearingId"))
				)

                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN11")))

				.pause(MinThinkTime, MaxThinkTime)
			}   

      val EditHearing =
          group("XUI_PCS_Caseworker_AmendHearing_12_ChooseEditHearing") {
				exec(http("XUI_PCS_Caseworker_AmendHearing_12_ChooseEditHearing")
					.post("/data/case-types/PCS/validate?pageId=manageHearingmanageHearing")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Origin", BaseURL)
					.header("experimental", "true")
					.header("Priority", "u=0")
					.header("Client-Context", "eyJjbGllbnRfY29udGV4dCI6eyJ1c2VyX2xhbmd1YWdlIjp7Imxhbmd1YWdlIjoiZW4ifX19")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.case-data-validate.v2+json;charset=UTF-8")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN11}")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					//.body(StringBody("{\"data\":{\"showManageHearingPage\":\"YES\",\"manageHearingOption\":\"EDIT\",\"selectedHearingId\":null,\"mhDraftPartyList\":null,\"hearing_HearingId\":\"932"\",\"hearing_HearingSummaryMarkdown\":\"#{HearingSummaryMarkdown}&nbsp;</p>\",\"mhDraft_HearingId\":null,\"mhDraft_HearingSummaryMarkdown\":null,\"mhDraft_Type\":null,\"mhDraft_OtherHearingType\":null,\"mhDraft_NoticeWording\":null,\"mhDraft_Date\":null,\"mhDraft_DurationDays\":null,\"mhDraft_DurationHours\":null,\"mhDraft_DurationMinutes\":null,\"mhDraft_Notes\":null,\"mhDraft_IssueNotice\":null,\"mhDraft_IsWithoutNotice\":null,\"mhDraft_AdditionalInformation\":null,\"mhDraft_CancellationReason\":null},\"event\":{\"id\":\"manageHearing\",\"summary\":\"\",\"description\":\"\"},\"event_data\":{\"showManageHearingPage\":\"YES\",\"manageHearingOption\":\"EDIT\",\"selectedHearingId\":null,\"mhDraftPartyList\":null,\"hearing_HearingId\":\932\",\"hearing_HearingSummaryMarkdown\":\"#{HearingSummaryMarkdown}&nbsp;</p>\",\"mhDraft_HearingId\":null,\"mhDraft_HearingSummaryMarkdown\":null,\"mhDraft_Type\":null,\"mhDraft_OtherHearingType\":null,\"mhDraft_NoticeWording\":null,\"mhDraft_Date\":null,\"mhDraft_DurationDays\":null,\"mhDraft_DurationHours\":null,\"mhDraft_DurationMinutes\":null,\"mhDraft_Notes\":null,\"mhDraft_IssueNotice\":null,\"mhDraft_IsWithoutNotice\":null,\"mhDraft_AdditionalInformation\":null,\"mhDraft_CancellationReason\":null},\"event_token\":\"#{event_token1}\",\"ignore_warning\":false,\"case_reference\":\"#{caseId}\"}"))
                    .body(StringBody("""{"data":{"showManageHearingPage":"YES","manageHearingOption":"EDIT","selectedHearingId":null,"mhDraftPartyList":null,"hearing_HearingId":"932","hearing_HearingSummaryMarkdown":"#{HearingSummaryMarkdown}&nbsp;</p>","mhDraft_HearingId":null,"mhDraft_HearingSummaryMarkdown":null,"mhDraft_Type":null,"mhDraft_OtherHearingType":null,"mhDraft_NoticeWording":null,"mhDraft_Date":null,"mhDraft_DurationDays":null,"mhDraft_DurationHours":null,"mhDraft_DurationMinutes":null,"mhDraft_Notes":null,"mhDraft_IssueNotice":null,"mhDraft_IsWithoutNotice":null,"mhDraft_AdditionalInformation":null,"mhDraft_CancellationReason":null},"event":{"id":"manageHearing","summary":"","description":""},"event_data":{"showManageHearingPage":"YES","manageHearingOption":"EDIT","selectedHearingId":null,"mhDraftPartyList":null,"hearing_HearingId":"932","hearing_HearingSummaryMarkdown":"#{HearingSummaryMarkdown}&nbsp;</p>","mhDraft_HearingId":null,"mhDraft_HearingSummaryMarkdown":null,"mhDraft_Type":null,"mhDraft_OtherHearingType":null,"mhDraft_NoticeWording":null,"mhDraft_Date":null,"mhDraft_DurationDays":null,"mhDraft_DurationHours":null,"mhDraft_DurationMinutes":null,"mhDraft_Notes":null,"mhDraft_IssueNotice":null,"mhDraft_IsWithoutNotice":null,"mhDraft_AdditionalInformation":null,"mhDraft_CancellationReason":null},"event_token":"#{event_token1}","ignore_warning":false,"case_reference":"#{caseId}"}"""))
				)
				.pause(MinThinkTime, MaxThinkTime)
          }
         .group("XUI_PCS_Caseworker_AmendHearing_13_EditHearingContinue") {
				exec(http("XUI_PCS_Caseworker_AmendHearing_13_EditHearingContinue")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("traceparent", "00-f55c5667db1540c0a4848a18d07ecdac-47e6d9e6927741d2-01")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
                 .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN12")))
                 
				.exec(http("/data/case-types/PCS/validate?pageId=manageHearinghearingDetails")
					.post("/data/case-types/PCS/validate?pageId=manageHearinghearingDetails")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Origin", BaseURL)
					.header("experimental", "true")
					.header("Priority", "u=0")
					.header("Client-Context", "eyJjbGllbnRfY29udGV4dCI6eyJ1c2VyX2xhbmd1YWdlIjp7Imxhbmd1YWdlIjoiZW4ifX19")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.case-data-validate.v2+json;charset=UTF-8")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN12}")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					//.body(StringBody("{\"data\":{\"hearingLocation\":\"#{hearingLocation}\",\"hearing_Type\":\"#{TypeofHearing}\",\"hearing_NoticeWording\":\"#{WordingOfHearing}\",\"hearing_Date\":\"2028-02-03T00:00:00.000\",\"hearing_DurationDays\":\"1\",\"hearing_DurationHours\":\"1\",\"hearing_DurationMinutes\":\"10\",\"hearing_Notes\":\"hearing testing for further discussion on claim issues\",\"hearing_IssueNotice\":\"NO\",\"hearing_AdditionalInformation\":\"Testing\"},\"event\":{\"id\":\"manageHearing\",\"summary\":\"\",\"description\":\"\"},\"event_data\":{\"showManageHearingPage\":\"YES\",\"manageHearingOption\":\"EDIT\",\"selectedHearingId\":\932\",\"mhDraftPartyList\":null,\"  \":\932\",\"hearing_HearingSummaryMarkdown\":\"#{HearingSummaryMarkdown}&nbsp;</p>\",\"mhDraft_HearingId\":null,\"mhDraft_HearingSummaryMarkdown\":null,\"mhDraft_Type\":null,\"mhDraft_OtherHearingType\":null,\"mhDraft_NoticeWording\":null,\"mhDraft_Date\":null,\"mhDraft_DurationDays\":null,\"mhDraft_DurationHours\":null,\"mhDraft_DurationMinutes\":null,\"mhDraft_Notes\":null,\"mhDraft_IssueNotice\":null,\"mhDraft_IsWithoutNotice\":null,\"mhDraft_AdditionalInformation\":null,\"mhDraft_CancellationReason\":null,\"hearingLocation\":\"#{hearingLocation}\",\"hearing_Type\":\"#{TypeofHearing}\",\"hearing_NoticeWording\":\"#{WordingOfHearing}\",\"hearing_Date\":\"2028-02-03T00:00:00.000\",\"hearing_DurationDays\":\"1\",\"hearing_DurationHours\":\"1\",\"hearing_DurationMinutes\":\"10\",\"hearing_Notes\":\"hearing testing for further discussion on claim issues\",\"hearing_IssueNotice\":\"NO\",\"hearing_AdditionalInformation\":\"Testing\"},\"event_token\":\"#{event_token1}\",\"ignore_warning\":false,\"case_reference\":\"#{caseId}\"}"))
				    .body(StringBody("""{"data":{"hearingLocation":"#{hearingLocation}","hearing_Type":"#{TypeofHearing}","hearing_NoticeWording":"#{WordingOfHearing}","hearing_Date":"2028-02-03T00:00:00.000","hearing_DurationDays":"1","hearing_DurationHours":"1","hearing_DurationMinutes":"10","hearing_Notes":"hearing testing for further discussion on claim issues","hearing_IssueNotice":"NO","hearing_AdditionalInformation":"Testing"},"event":{"id":"manageHearing","summary":"","description":""},"event_data":{"showManageHearingPage":"YES","manageHearingOption":"EDIT","selectedHearingId":null,"mhDraftPartyList":null,"hearing_HearingId":"932","hearing_HearingSummaryMarkdown":"#{HearingSummaryMarkdown}&nbsp;</p>","mhDraft_HearingId":null,"mhDraft_HearingSummaryMarkdown":null,"mhDraft_Type":null,"mhDraft_NoticeWording":null,"mhDraft_Date":null,"mhDraft_DurationDays":null,"mhDraft_DurationHours":null,"mhDraft_DurationMinutes":null,"mhDraft_Notes":null,"mhDraft_IssueNotice":null,"mhDraft_IsWithoutNotice":null,"mhDraft_AdditionalInformation":null,"mhDraft_CancellationReason":null,"hearingLocation":"#{hearingLocation}","hearing_Type":"#{TypeofHearing}","hearing_NoticeWording":"#{WordingOfHearing}","hearing_Date":"2028-02-03T00:00:00.000","hearing_DurationDays":"1","hearing_DurationHours":"1","hearing_DurationMinutes":"10","hearing_Notes":"hearing testing for further discussion on claim issues","hearing_IssueNotice":"NO","hearing_AdditionalInformation":"Testing"},"event_token":"#{event_token1}","ignore_warning":false,"case_reference":"#{caseId}"}"""))
                )
				.pause(MinThinkTime, MaxThinkTime)
			}
		    .group("XUI_PCS_Caseworker_AmendHearing_14_Submit") {
				exec(http("XUI_PCS_Caseworker_AmendHearing_14_Submit")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("traceparent", "00-f55c5667db1540c0a4848a18d07ecdac-75df14fb470f4d22-01")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)

                .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN13")))

				.exec(http("/data/cases/#{caseId}/events")
					.post("/data/cases/#{caseId}/events")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Origin", BaseURL)
					.header("experimental", "true")
					.header("Priority", "u=0")
					.header("Client-Context", "eyJjbGllbnRfY29udGV4dCI6eyJ1c2VyX2xhbmd1YWdlIjp7Imxhbmd1YWdlIjoiZW4ifX19")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.create-event.v2+json;charset=UTF-8")
					.formParam("X-XSRF-TOKEN", "${XSRF-TOKEN13}")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
					.header("Sec-Fetch-Dest", "empty")
					.body(StringBody("{\"data\":{\"showManageHearingPage\":\"YES\",\"manageHearingOption\":\"EDIT\",\"selectedHearingId\":\"#{hearingId}\",\"mhDraftPartyList\":null,\"hearing_HearingId\":\"#{hearingId}\",\"hearing_HearingSummaryMarkdown\":\"#{HearingSummaryMarkdown}&nbsp;</p>\",\"mhDraft_HearingId\":\"932\",\"mhDraft_HearingSummaryMarkdown\":\"#{HearingSummaryMarkdown}&nbsp;</p>\",\"mhDraft_Type\":\"#{TypeofHearing}\",\"mhDraft_OtherHearingType\":null,\"mhDraft_NoticeWording\":\"#{WordingOfHearing}\",\"mhDraft_Date\":\"2028-02-03T00:00:00\",\"mhDraft_DurationDays\":\"1\",\"mhDraft_DurationHours\":\"1\",\"mhDraft_DurationMinutes\":\"10\",\"mhDraft_Notes\":\"hearing testing for further discussion on claim issues\",\"mhDraft_IssueNotice\":\"NO\",\"mhDraft_IsWithoutNotice\":null,\"mhDraft_AdditionalInformation\":\"Testing\",\"mhDraft_CancellationReason\":null,\"hearingLocation\":\"#{hearingLocation}\",\"hearing_Type\":\"#{TypeofHearing}\",\"hearing_NoticeWording\":\"#{WordingOfHearing}\",\"hearing_Date\":\"2028-02-03T00:00:00\",\"hearing_DurationDays\":\"1\",\"hearing_DurationHours\":\"1\",\"hearing_DurationMinutes\":\"10\",\"hearing_Notes\":\"hearing testing for further discussion on claim issues\",\"hearing_IssueNotice\":\"NO\",\"hearing_AdditionalInformation\":\"Testing\"},\"event\":{\"id\":\"manageHearing\",\"summary\":\"\",\"description\":\"\"},\"event_token\":\"#{event_token1}\",\"ignore_warning\":false}"))
                )
				.exec(http("/data/internal/cases/#{caseId}")
					.get("/data/internal/cases/#{caseId}")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("experimental", "true")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-case-view.v2+json")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.pause(MinThinkTime, MaxThinkTime)

                
               .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRF-TOKEN14")))
			}

      val HistroryView =
          group("XUI_PCS_Caseworker_AmendHearing_15_ClickHistoryTab") {
				exec(http("XUI_PCS_Caseworker_AmendHearing_15_ClickHistoryTab")
					.get("/auth/keepalive")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
				)
				.exec(http("/api/wa-supported-jurisdiction/get")
					.get("/api/wa-supported-jurisdiction/get")
					.headers(Headers.commonHeader)
        			.header("accept", "application/json")
					.header("Accept", "application/json, text/plain, */*")
					.header("Accept-Encoding", "gzip, deflate, br, zstd")
					.header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0")
                    .check(substring("PCS"))
				)
				.pause(MinThinkTime, MaxThinkTime)
			}
      val ClickView =
           group("XUI_PCS_Caseworker_CancelHearing_16_SelectMangeHearing") {
			    exec(http("XUI_PCS_Caseworker_CancelHearing_16_SelectMangeHearing")
					.get("/auth/keepalive")
					.header("Accept", "application/json, text/plain, */*")
				)
				.exec(http("/workallocation/case/tasks/#{caseId}/event/manageHearing/caseType/PCS/jurisdiction/PCS")
					.get("/workallocation/case/tasks/#{caseId}/event/manageHearing/caseType/PCS/jurisdiction/PCS")
					.header("Accept", "application/json")
				)
				.exec(http("/data/internal/cases/#{caseId}/event-triggers/manageHearing")
					.get("/data/internal/cases/#{caseId}/event-triggers/manageHearing")
					.header("experimental", "true")
					.header("Client-Context", "eyJjbGllbnRfY29udGV4dCI6eyJ1c2VyX2xhbmd1YWdlIjp7Imxhbmd1YWdlIjoiZW4ifX19")
					.header("Accept", "application/vnd.uk.gov.hmcts.ccd-data-store-api.ui-start-event-trigger.v2+json;charset=UTF-8")
					.queryParam("ignore-warning", "false")
					.check(regex("event_token\":\"(.*?)\",\"wizard_pages").saveAs("event_token2"))
                    .check(jsonPath("$.case_fields[?(@.id == 'hearing_CancellationReason')].display_context").is("MANDATORY"))
				)
				.pause(MinThinkTime, MaxThinkTime)
			}
        
} 

